import { storyBotSmallHeader, bigText, subtitle, storyDiv, nameNumber, name, sentenceP, clickableP, wait, bigGreenActionButton, footerDiv, gameInstruction, footerDiv2 } from "./styles.module.scss"
import React, {useState} from "react";
import classNames from 'classnames';
import {ISubmissionMessage} from "../game_logic/IGameLogic";

type GameoverProps = {
    messages: ISubmissionMessage[]
    playAgainFn: () => void
}

const colors = [
    '#CDE1A5',
    '#E1D3A5',
    '#DEA5E1',
    '#A5C2E1',
    '#E1CBA5',
    '#A5E1D6',
]

const returnHeader = (gameStatus: string) => {
    if (gameStatus === 'win') {
        return <h2 className={bigText} style={{color: '#7CBE66', marginTop: '2vh', marginBottom: '2vh'}}>You win!!!</h2>
    }
    if (gameStatus === 'lose') {
        return <h2 className={bigText} style={{color: '#A64848', marginTop: '2vh', marginBottom: '2vh'}}>You lose!!!</h2>
    }
    return <h2 className={bigText} style={{marginTop: '2vh', marginBottom: '2vh'}}>Game’s over!</h2>
}

const returnFooter = (gameStatus: string, messages: ISubmissionMessage[], playAgainfn: () => void) => {
    if (gameStatus === "unresolved") {
        return <div className={footerDiv}>
            <h2 className={wait}>BUT WAIT!!!</h2>
            <h3 className={gameInstruction}>There was an an AI imposter playing with you!!</h3>
            <h3 className={gameInstruction}><b>Can you identify the sentence that was generated by AI?</b></h3>
            <h3 className={gameInstruction}>Click on the sentence you believe was generated by AI.</h3>
        </div>
    }

    return <div className={footerDiv2}>
        <div>
            {messages.map((v, i) => {
                return (<tr>
                    <td className={nameNumber}>{i}</td>
                    <td className={name} style={{backgroundColor: colors[i]}}>{v.name}</td>
                </tr>)
            })}
        </div>
        <div style={{width: "600px"}}>
            {gameStatus === "win" && (<h3 className={gameInstruction}>Since you won, you get a cookie. </h3>)}
            {gameStatus === "lose" &&
                (<h3 className={gameInstruction}>Since you lost, one of your friends will lose their job. Your friends are
                    indistinguishable from AI, so corporate says they must be replaced by robots.</h3>)}
            <button className={bigGreenActionButton} style={{marginTop: "2px"}} onClick={(e) => {
                playAgainfn()
            }}>Play again?</button>
        </div>


    </div>

}

const Gameover: React.FC<GameoverProps> = (props) => {
    const [clickable, setClickable] = useState(true)
    const [gameStatus, setGameStatus] = useState("unresolved")

    const clicked = (idx: number) => {
        if (clickable) {
            setClickable(false)
            if (props.messages[idx].name === "AI") {
                setGameStatus("win")
            } else {
                setGameStatus("lose")
            }
        }
    }

    return (
        <div>
            <h1 className={storyBotSmallHeader}>StoryBot</h1>
            {returnHeader(gameStatus)}
            <h2 className={subtitle}><b>Here’s the story you wrote!!</b></h2>
            <div className={storyDiv}>
                {props.messages.map((v, i) => {
                    return (<p className={classNames(sentenceP, { [clickableP]: clickable })} style={{backgroundColor: colors[i]}} onClick={() => clicked(i)}> {v.sentence} </p>)
                })}
            </div>
            {returnFooter(gameStatus, props.messages, props.playAgainFn)}
        </div>
    )
}

export default Gameover
